extends Node

const PREVIEW_TEXTURES = {
	"Body": [
		"res://assets/sprites/Character Components/Body/Body_01.png",
		"res://assets/sprites/Character Components/Body/Body_02.png",
		"res://assets/sprites/Character Components/Body/Body_03.png",
		"res://assets/sprites/Character Components/Body/Body_04.png",
		"res://assets/sprites/Character Components/Body/Body_05.png",
		"res://assets/sprites/Character Components/Body/Body_06.png",
		"res://assets/sprites/Character Components/Body/Body_07.png",
		"res://assets/sprites/Character Components/Body/Body_08.png",
		"res://assets/sprites/Character Components/Body/Body_09.png",
	],
	"Hairstyle": [
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_01_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_02_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_03_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_04_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_05_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_06_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_07_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_08_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_09_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_10_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_11_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_12_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_13_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_14_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_15_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_16_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_17_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_18_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_19_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_20_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_21_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_22_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_23_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_24_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_25_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_26_07.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_27_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_28_06.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_01.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_02.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_03.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_04.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_05.png",
		"res://assets/sprites/Character Components/Hairstyle/Hairstyle_29_06.png",
	],
	"Eyes": [
		"res://assets/sprites/Character Components/Eyes/Eyes_01.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_02.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_03.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_04.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_05.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_06.png",
		"res://assets/sprites/Character Components/Eyes/Eyes_07.png",
	],
	"Outfit": [
		"res://assets/sprites/Character Components/Outfit/Outfit_01_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_06.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_07.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_08.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_09.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_01_10.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_02_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_02_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_02_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_02_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_03_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_03_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_03_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_03_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_04_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_04_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_04_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_05_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_05_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_05_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_05_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_05_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_06_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_06_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_06_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_06_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_07_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_07_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_07_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_07_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_08_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_08_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_08_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_09_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_09_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_09_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_10_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_10_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_10_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_10_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_10_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_11_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_11_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_11_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_11_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_12_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_12_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_12_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_13_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_13_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_13_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_13_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_14_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_14_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_14_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_14_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_14_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_15_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_15_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_15_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_16_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_16_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_16_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_17_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_17_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_17_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_18_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_18_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_18_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_18_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_19_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_19_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_19_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_19_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_20_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_20_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_20_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_21_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_21_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_21_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_21_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_22_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_22_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_22_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_22_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_23_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_23_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_23_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_23_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_24_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_24_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_24_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_24_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_25_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_25_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_25_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_25_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_25_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_26_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_26_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_26_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_27_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_27_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_27_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_28_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_28_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_28_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_28_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_29_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_29_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_29_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_29_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_30_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_30_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_30_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_31_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_31_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_31_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_31_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_31_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_32_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_32_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_32_03.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_32_04.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_32_05.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_33_01.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_33_02.png",
		"res://assets/sprites/Character Components/Outfit/Outfit_33_03.png",
	],
	"Accessory": [
		"res://assets/sprites/Character Components/Accessory/Accessory_01_Ladybug_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_01_Ladybug_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_01_Ladybug_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_01_Ladybug_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_02_Bee_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_02_Bee_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_02_Bee_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_06.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_07.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_08.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_09.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_03_Backpack_10.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_04_Snapback_06.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_05_Dino_Snapback_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_05_Dino_Snapback_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_05_Dino_Snapback_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_06_Policeman_Hat_06.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_07_Bataclava_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_07_Bataclava_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_07_Bataclava_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_08_Detective_Hat_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_08_Detective_Hat_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_08_Detective_Hat_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_09_Zombie_Brain_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_09_Zombie_Brain_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_09_Zombie_Brain_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_10_Bolt_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_10_Bolt_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_10_Bolt_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_11_Beanie_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_11_Beanie_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_11_Beanie_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_11_Beanie_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_11_Beanie_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_12_Mustache_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_12_Mustache_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_12_Mustache_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_12_Mustache_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_12_Mustache_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_13_Beard_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_13_Beard_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_13_Beard_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_13_Beard_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_13_Beard_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_14_Gloves_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_14_Gloves_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_14_Gloves_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_14_Gloves_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_15_Glasses_06.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_16_Monocle_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_16_Monocle_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_16_Monocle_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_17_Medical_Mask_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_17_Medical_Mask_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_17_Medical_Mask_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_17_Medical_Mask_04.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_17_Medical_Mask_05.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_18_Chef_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_18_Chef_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_18_Chef_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_19_Party_Cone_01.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_19_Party_Cone_02.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_19_Party_Cone_03.png",
		"res://assets/sprites/Character Components/Accessory/Accessory_19_Party_Cone_04.png",
	],
}

const COMPONENT_ANIM_PATHS = {
	"body": [
		"res://resources/character_components_animations/body/Body_01.tres",
		"res://resources/character_components_animations/body/Body_02.tres",
		"res://resources/character_components_animations/body/Body_03.tres",
		"res://resources/character_components_animations/body/Body_04.tres",
		"res://resources/character_components_animations/body/Body_05.tres",
		"res://resources/character_components_animations/body/Body_06.tres",
		"res://resources/character_components_animations/body/Body_07.tres",
		"res://resources/character_components_animations/body/Body_08.tres",
		"res://resources/character_components_animations/body/Body_09.tres",
	],
	"hairstyle": [
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_01_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_02_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_03_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_04_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_05_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_06_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_07_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_08_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_09_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_10_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_11_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_12_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_13_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_14_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_15_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_16_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_17_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_18_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_19_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_20_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_21_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_22_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_23_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_24_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_25_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_26_07.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_27_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_28_06.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_01.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_02.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_03.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_04.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_05.tres",
		"res://resources/character_components_animations/hairstyle/Hairstyle_29_06.tres",
	],
	"eyes": [
		"res://resources/character_components_animations/eyes/Eyes_01.tres",
		"res://resources/character_components_animations/eyes/Eyes_02.tres",
		"res://resources/character_components_animations/eyes/Eyes_03.tres",
		"res://resources/character_components_animations/eyes/Eyes_04.tres",
		"res://resources/character_components_animations/eyes/Eyes_05.tres",
		"res://resources/character_components_animations/eyes/Eyes_06.tres",
		"res://resources/character_components_animations/eyes/Eyes_07.tres",
	],
	"outfit": [
		"res://resources/character_components_animations/outfit/Outfit_01_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_06.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_07.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_08.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_09.tres",
		"res://resources/character_components_animations/outfit/Outfit_01_10.tres",
		"res://resources/character_components_animations/outfit/Outfit_02_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_02_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_02_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_02_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_03_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_03_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_03_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_03_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_04_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_04_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_04_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_05_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_05_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_05_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_05_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_05_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_06_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_06_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_06_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_06_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_07_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_07_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_07_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_07_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_08_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_08_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_08_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_09_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_09_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_09_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_10_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_10_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_10_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_10_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_10_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_11_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_11_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_11_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_11_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_12_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_12_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_12_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_13_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_13_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_13_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_13_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_14_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_14_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_14_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_14_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_14_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_15_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_15_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_15_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_16_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_16_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_16_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_17_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_17_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_17_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_18_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_18_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_18_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_18_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_19_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_19_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_19_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_19_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_20_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_20_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_20_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_21_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_21_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_21_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_21_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_22_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_22_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_22_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_22_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_23_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_23_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_23_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_23_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_24_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_24_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_24_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_24_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_25_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_25_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_25_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_25_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_25_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_26_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_26_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_26_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_27_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_27_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_27_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_28_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_28_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_28_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_28_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_29_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_29_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_29_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_29_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_30_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_30_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_30_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_31_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_31_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_31_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_31_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_31_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_32_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_32_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_32_03.tres",
		"res://resources/character_components_animations/outfit/Outfit_32_04.tres",
		"res://resources/character_components_animations/outfit/Outfit_32_05.tres",
		"res://resources/character_components_animations/outfit/Outfit_33_01.tres",
		"res://resources/character_components_animations/outfit/Outfit_33_02.tres",
		"res://resources/character_components_animations/outfit/Outfit_33_03.tres",
	],
	"accessory": [
		"res://resources/character_components_animations/accessory/Accessory_01_Ladybug_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_01_Ladybug_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_01_Ladybug_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_01_Ladybug_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_02_Bee_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_02_Bee_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_02_Bee_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_06.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_07.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_08.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_09.tres",
		"res://resources/character_components_animations/accessory/Accessory_03_Backpack_10.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_04_Snapback_06.tres",
		"res://resources/character_components_animations/accessory/Accessory_05_Dino_Snapback_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_05_Dino_Snapback_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_05_Dino_Snapback_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_06_Policeman_Hat_06.tres",
		"res://resources/character_components_animations/accessory/Accessory_07_Bataclava_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_07_Bataclava_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_07_Bataclava_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_08_Detective_Hat_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_08_Detective_Hat_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_08_Detective_Hat_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_09_Zombie_Brain_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_09_Zombie_Brain_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_09_Zombie_Brain_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_10_Bolt_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_10_Bolt_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_10_Bolt_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_11_Beanie_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_11_Beanie_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_11_Beanie_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_11_Beanie_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_11_Beanie_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_12_Mustache_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_12_Mustache_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_12_Mustache_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_12_Mustache_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_12_Mustache_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_13_Beard_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_13_Beard_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_13_Beard_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_13_Beard_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_13_Beard_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_14_Gloves_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_14_Gloves_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_14_Gloves_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_14_Gloves_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_15_Glasses_06.tres",
		"res://resources/character_components_animations/accessory/Accessory_16_Monocle_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_16_Monocle_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_16_Monocle_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_17_Medical_Mask_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_17_Medical_Mask_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_17_Medical_Mask_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_17_Medical_Mask_04.tres",
		"res://resources/character_components_animations/accessory/Accessory_17_Medical_Mask_05.tres",
		"res://resources/character_components_animations/accessory/Accessory_18_Chef_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_18_Chef_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_18_Chef_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_19_Party_Cone_01.tres",
		"res://resources/character_components_animations/accessory/Accessory_19_Party_Cone_02.tres",
		"res://resources/character_components_animations/accessory/Accessory_19_Party_Cone_03.tres",
		"res://resources/character_components_animations/accessory/Accessory_19_Party_Cone_04.tres",
	],
}
